spring:
  datasource:
    url: jdbc:h2:file:./contest
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
server:
  port: 8082